In [4]:
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression

In [5]:
from sklearn.datasets import fetch_california_housing
bs = fetch_california_housing()

In [6]:
bs.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [7]:
print(bs['DESCR'])

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.

In [8]:
 bs['data']

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8))

In [9]:
bs['target']

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,))

In [10]:
bs['target_names'][0]

'MedHouseVal'

In [11]:
cal_housing_data = pd.DataFrame(data = bs['data'] ,columns = bs['feature_names'] )
cal_housing_data[bs['target_names'][0]]  = bs['target']

In [12]:
cal_housing_data.head(4)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413

In [13]:
corr = cal_housing_data.corr()
corr

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
MedInc,1.000000,-0.119034,0.326895,-0.062040,0.004834,0.018766,-0.079809,-0.015176,0.688075
HouseAge,-0.119034,1.000000,-0.153277,-0.077747,-0.296244,0.013191,0.011173,-0.108197,0.105623
AveRooms,0.326895,-0.153277,1.000000,0.847621,-0.072213,-0.004852,0.106389,-0.027540,0.151948
AveBedrms,-0.062040,-0.077747,0.847621,1.000000,-0.066197,-0.006181,0.069721,0.013344,-0.046701
Population,0.004834,-0.296244,-0.072213,-0.066197,1.000000,0.069863,-0.108785,0.099773,-0.024650
AveOccup,0.018766,0.013191,-0.004852,-0.006181,0.069863,1.000000,0.002366,0.002476,-0.023737
Latitude,-0.079809,0.011173,0.106389,0.069721,-0.108785,0.002366,1.000000,-0.924664,-0.144160
Longitude,-0.015176,-0.108197,-0.027540,0.013344,0.099773,0.002476,-0.924664,1.000000,-0.045967
MedHouseVal,0.688075,0.105623,0.151948,-0.046701,-0.024650,-0.023737,-0.144160,-0.045967,1.000000

In [14]:
corr[((corr > 0.4) | (corr < -0.4)) & (corr != 1)].fillna('')

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
MedInc,,,,,,,,,0.688075
HouseAge,,,,,,,,,
AveRooms,,,,0.847621,,,,,
AveBedrms,,,0.847621,,,,,,
Population,,,,,,,,,
AveOccup,,,,,,,,,
Latitude,,,,,,,,-0.924664,
Longitude,,,,,,,-0.924664,,
MedHouseVal,0.688075,,,,,,,,

In [15]:
kf1 = KFold(n_splits = 5)

In [16]:
kf1

KFold(n_splits=5, random_state=None, shuffle=False)

In [17]:
kf1.split(cal_housing_data)

In [18]:
for train_data_index , test_data_index in kf1.split(cal_housing_data):
    
    print(train_data_index)
    print(test_data_index, '\n\n')

    # using these index we can get the train and test rows
    # train_data = cal_housing_data.loc[train_data_index , [x_cols]]
    # test_data = cal_housing_data.loc[test_data_index , y_col ]
    
    # we can make a model inside this loop and store the results( mape) in a list
    # then we can compare

[ 4128  4129  4130 ... 20637 20638 20639]
[   0    1    2 ... 4125 4126 4127]


[    0     1     2 ... 20637 20638 20639]
[4128 4129 4130 ... 8253 8254 8255]


[    0     1     2 ... 20637 20638 20639]
[ 8256  8257  8258 ... 12381 12382 12383]


[    0     1     2 ... 20637 20638 20639]
[12384 12385 12386 ... 16509 16510 16511]


[    0     1     2 ... 16509 16510 16511]
[16512 16513 16514 ... 20637 20638 20639]

### 2nd method easier one to implement and use

In [21]:
from sklearn.model_selection import cross_val_score
lr = LinearRegression()

scores = cross_val_score(lr,   # model that should be built on all the sets od data
                         cal_housing_data.drop(columns = ['MedHouseVal']) , # x --> prdictors
                         cal_housing_data['MedHouseVal'],  # y  --> label / dependent
                         cv = 5 ,  # number of splits
                         scoring = 'r2')
scores

array([0.54866323, 0.46820691, 0.55078434, 0.53698703, 0.66051406])

In [22]:
print(scores.mean().round(2))
print(scores.std().round(2))

0.55
0.06