In [2]:
%pip install scikit-learn
import pandas as pd
import sklearn as sk
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Requirement already satisfied: scikit-learn in /Users/pradeeppaladugula/Github Projects/pp-ai-ml-2026/.venv/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /Users/pradeeppaladugula/Github Projects/pp-ai-ml-2026/.venv/lib/python3.14/site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in /Users/pradeeppaladugula/Github Projects/pp-ai-ml-2026/.venv/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Users/pradeeppaladugula/Github Projects/pp-ai-ml-2026/.venv/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/pradeeppaladugula/Github Projects/pp-ai-ml-2026/.venv/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

Matplotlib is building the font cache; this may take a moment.

In [2]:
df = pd.read_csv('tips.csv')

In [3]:
df

     total_bill   tip  gender smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## One Hot encoding

In [8]:
df = pd.get_dummies(df , columns = ['day'])

In [9]:
df

,total_bill,tip,gender,smoker,time,size,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,Female,No,Dinner,2,False,False,True,False
1,10.34,1.66,Male,No,Dinner,3,False,False,True,False
2,21.01,3.50,Male,No,Dinner,3,False,False,True,False
3,23.68,3.31,Male,No,Dinner,2,False,False,True,False
4,24.59,3.61,Female,No,Dinner,4,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Dinner,3,False,True,False,False
240,27.18,2.00,Female,Yes,Dinner,2,False,True,False,False
241,22.67,2.00,Male,Yes,Dinner,2,False,True,False,False
242,17.82,1.75,Male,No,Dinner,2,False,True,False,False
243,18.78,3.00,Female,No,Dinner,2,False,False,False,True

## Label Encoding

In [11]:
df['gender'].map({'Male' : 0 , 'Female' : 1})

0      1
1      0
2      0
3      0
4      1
      ..
239    0
240    1
241    0
242    0
243    1
Name: gender, Length: 244, dtype: int64

In [12]:
df['gender'].astype('category').cat.codes

0      0
1      1
2      1
3      1
4      0
      ..
239    1
240    0
241    1
242    1
243    0
Length: 244, dtype: int8

In [ ]:
# most recommended
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [16]:
lb.fit_transform(df['gender'])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [17]:
lb.classes_

array(['Female', 'Male'], dtype=object)

In [18]:
lb.inverse_transform([0,0,0,1])

array(['Female', 'Female', 'Female', 'Male'], dtype=object)

## Ordinal encoding

In [25]:
test_df = pd.DataFrame({'size': ['small', 'medium', 'large', 'medium', 'small', 'large'],
                        'quality' : ['low' , 'low' , 'medium', 'low', 'high', 'high']})

In [26]:
test_df

     size quality
0   small     low
1  medium     low
2   large  medium
3  medium     low
4   small    high
5   large    high

In [27]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [   ['small', 'medium', 'large']  , ['low', 'medium', 'high']  ])

In [28]:
oe.fit_transform(test_df)

array([[0., 0.],
       [1., 0.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [2., 2.]])

In [29]:
pd.DataFrame(data = oe.fit_transform(test_df) , columns = test_df.columns)

   size  quality
0   0.0      0.0
1   1.0      0.0
2   2.0      1.0
3   1.0      0.0
4   0.0      2.0
5   2.0      2.0